name: FoD issues to GitHub (MultiTool)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: fortify/gha-fod-download-fpr@master
        with:
          base-url: https://ams.fortify.com
          tenant: ${{ secrets.FOD_TENANT }}
          user: ${{ secrets.FOD_USER }}
          password: ${{ secrets.FOD_PAT }}
          release-id: ${{ secrets.FOD_RELEASE_ID }}
          outputDir: ./fpr
      - uses: fortify/gha-fpr-to-sarif@use-mt-dsp-flag
        with:
          input: ./fpr
          outputDir: ./sarif
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./sarif
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: fpr-files
          path: ./fpr
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: sarif-files
          path: ./sarif
